- name: Commit and push
  uses: EndBug/add-and-commit@v9
  with:
    author_name: 'Izaquielsantos'
    author_email: 'Izaquielsantos@users.noreply.github.com'
    message: 'Atualizando a cobrinha ğŸ'
    push: true
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
